function AwardListCtrl($scope) {
  $scope.awards = [
  {
    "applicant_town": "Glasgow", 
    "title": "Sound Chamber ", 
    "date_recd": "08/08/2011", 
    "s_parlcon_name": "Glasgow Kelvin", 
    "award_requested": "8,367 ", 
    "s_parlreg_name": "Glasgow", 
    "date_created": "11/08/2011", 
    "investment_type": "Managed Fund ", 
    "applicant_postcode": "G1 1NQ", 
    "value": "8,367 ", 
    "description": "Support towards project management costs and expenses for guest speakers and delegates to Sound Chamber, industry event and showcasing Scotland_s ensemble music.", 
    "date_decision_made": "11/08/2011", 
    "council_area_name": "Glasgow City", 
    "proj_ref": "11-02244", 
    "award_decision": "Approved", 
    "investment_route": "New Investment Programmes", 
    "applicant_name": "Chamber Music Forum Scotland", 
    "award_description": "Quality Production Arts"
  }, 
  {
    "applicant_town": "Edinburgh", 
    "title": "Children in Scotland_s Conference", 
    "date_recd": "27/03/2012", 
    "s_parlcon_name": "Edinburgh Central", 
    "award_requested": "3,000 ", 
    "s_parlreg_name": "Lothian", 
    "date_created": "27/03/2012", 
    "investment_type": "Managed Fund ", 
    "applicant_postcode": "EH2 4RG", 
    "value": "3,000 ", 
    "description": "To sponsor Children in Scotland_s conference in the year of Creative Scotland and to launch their new publication _welcome to the world_.", 
    "date_decision_made": "26/03/2012", 
    "council_area_name": "Edinburgh, City of", 
    "proj_ref": "12-3275\n", 
    "award_decision": "Approved", 
    "investment_route": "Education", 
    "applicant_name": "Children in Scotland", 
    "award_description": "Access, Audience and Participation"
  }, 
  {
    "applicant_town": "Glasgow", 
    "title": "Children_s Classic Concerts", 
    "date_recd": "15/06/2011", 
    "s_parlcon_name": "Glasgow Kelvin", 
    "award_requested": "19,300 ", 
    "s_parlreg_name": "Glasgow", 
    "date_created": "22/06/2011", 
    "investment_type": "Open Fund", 
    "applicant_postcode": "G11 5LP", 
    "value": "15,000 ", 
    "description": "Five concerts will be performed in total to a potential audience of 1800.", 
    "date_decision_made": "02/08/2011", 
    "council_area_name": "Glasgow City", 
    "proj_ref": "11-02111", 
    "award_decision": "Approved", 
    "investment_route": "Distribution of Existing Work", 
    "applicant_name": "Children_s Classic Concerts", 
    "award_description": "Touring, Festivals and Events"
  }, 
  {
    "applicant_town": "Glasgow", 
    "title": "Children_s Classic Concerts", 
    "date_recd": "24/10/2011", 
    "s_parlcon_name": "Glasgow Kelvin", 
    "award_requested": "11,961 ", 
    "s_parlreg_name": "Glasgow", 
    "date_created": "01/11/2011", 
    "investment_type": "Open Fund", 
    "applicant_postcode": "G11 5LP", 
    "value": "7,500 ", 
    "description": "In partnership with Edinburgh zoo, a commission of a 5 minute piece for ensemble and choir from Eddie McGuire, reflecting Scottish and Chinese musical traditions, to celebrate the arrival of the new pandas and honour this git from the Chinese government.", 
    "date_decision_made": "05/12/2011", 
    "council_area_name": "Glasgow City", 
    "proj_ref": "11-02600", 
    "award_decision": "Approved", 
    "investment_route": "New Investment Programmes", 
    "applicant_name": "Children_s Classic Concerts", 
    "award_description": "Quality Production Arts"
  }, 
  {
    "applicant_town": "Glasgow", 
    "title": "ArtWorks Scotland artists peer to peer networks", 
    "date_recd": "05/10/2011", 
    "s_parlcon_name": "Glasgow Southside", 
    "award_requested": "9,000 ", 
    "s_parlreg_name": "Glasgow", 
    "date_created": "07/10/2011", 
    "investment_type": "Managed Fund ", 
    "applicant_postcode": "G5 9DS", 
    "value": "9,000 ", 
    "description": "To support Scottish Prisons Artists Network to explore the skillset needed for working in the Criminal Justice setting.", 
    "date_decision_made": "04/10/2011", 
    "council_area_name": "Glasgow City", 
    "proj_ref": "11-02397", 
    "award_decision": "Approved", 
    "investment_route": "Paul Hamlyn Foundation (Artwork Scotland)", 
    "applicant_name": "Citizens Theatre", 
    "award_description": "Talent Development "
  }
  ];
}